dataset:
  value: "fluids.incompressible.Gaussians.npz"
num_trajectories:
  value: 400
model_name:
  value: "T"
lr:
  value: 0.00005
lr_embedding_recovery:
  value: 0.0005
lr_time_embedding:
  value: 0.0005
weight_decay:
  value: 0.000001
lr_scheduler:
  value: "cosine"
warmup_ratio:
  value: 0.0
early_stopping_patience:
  value: 100 #200
num_epochs:
  value: 200 #200
batch_size:
  value: 16
max_grad_norm:
  value: 5.0
max_num_train_time_steps:
  value: 19
train_time_step_size:
  value: 1 
hole_data_path:
  value: "/data/group_data/sage_lab_complex_geometry/FPO_Cylinder_Multiple_Hole_HighRe_1600.npy"
no_hole_data_path:
  value: "/data/group_data/sage_lab_complex_geometry/FPO_Cylinder_Multiple_Hole_interRe_1600.npy"
alpha:
  value: 0.00
