_wandb:
    value:
        cli_version: 0.18.4
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.18.4
            "8":
                - 5
            "12": 0.18.4
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 401
learning_rate:
    value: 0.001
modes:
    value: 12
n_layers:
    value: 4
output_dim:
    value: 2
scheduler_gamma:
    value: 0.5
scheduler_step_size:
    value: 100
width:
    value: 32
