_wandb:
    value:
        cli_version: 0.19.1
        code_path: code/ViT/vit_basic.py
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 16
depth:
    value: 4
dim:
    value: 128
dim_head:
    value: 32
epochs:
    value: 200
heads:
    value: 4
image_size:
    value:
        - 128
        - 384
learning_rate:
    value: 0.001
patch_size:
    value:
        - 16
        - 16
