data:
  data_path: "/home/vhsingh/test/NS_LDC_reg-001.npy"
  batch_size: 16
  train_split: 0.8
  debug: false
wandb:
  project: "Research"
  entity: "ved100-carnegie-mellon-university"
  learning_rate: 0.001
  epochs: 401
  batch_size: 32
  scheduler_step_size: 100
  scheduler_gamma: 0.5

model:
  model_type: "FNO"      # Options: "FFNO", "FNO", etc.
  input_dim: 6       # For CE=7 and NS=5
  modes: 12
  width: 32
  output_dim: 5           # For CE=6 and NS=5
  n_layers: 4
  factor: 4
  retrain_fno: 42
  n_ff_layers: 2
  share_weight: true      # Only applicable for FFNO
  ff_weight_norm: true
  layer_norm: false

optimizer:
  type: "Adam"
  lr: 0.001
  weight_decay: 1e-4  

scheduler:
  type: "StepLR"
  step_size: 100
  gamma: 0.5